#%RAML 1.0 Trait
usage: Response used for data creation
responses:
  201:
    body:
      application/json:
        example: !include /exchange_modules/976b4325-7212-4160-803f-178ad40b281f/examples/1.0.1/Success/Created_201.raml
  400:
    body:
      application/json:
        example: !include /exchange_modules/976b4325-7212-4160-803f-178ad40b281f/examples/1.0.1/Errors/error_400.raml
  500:
    body:
      application/json:
        example: !include /exchange_modules/976b4325-7212-4160-803f-178ad40b281f/examples/1.0.1/Errors/error_500.raml
          